springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
    groups:
      enabled: true
    location: /openapi.yaml
    packagesToScan: []
    pathsToMatch: []
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    url: /v3/api-docs

spring:
  datasource:
    url: jdbc:postgresql://logisticsapp-postgresdb-logisticsapp.h.aivencloud.com:20567/defaultdb?sslmode=require
    username: ${DB_USERNAME}
    password: ${DB_Password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.spatial.dialect.postgis.PostgisDialect

geocoding:
  nominatim:
    api:
      url: "https://nominatim.openstreetmap.org/search"
    user-agent: "YourAppName/1.0 (Logistics API; your-contact-email@example.com)"

google:
  maps:
    api:
      key: ${GOOGLE_API_KEY}

logging:
  level:
    com.example.service.NominatimGeocodingServiceImpl: DEBUG
    com.example.service.AssignmentService: DEBUG  # Or TRACE

    com.example.service.GoogleDirectionsApiHelperServiceImpl: DEBUG # Or TRACE
