package com.example.model;

// Assuming VehicleStatus is an enum in this package (generated by OpenAPI)
// import com.example.model.VehicleStatus; // Ensure this import is correct

public class VehicleResponse {
  private String registrationNumber;
  private String vehicleType;
  private Float capacity; // e.g., weight capacity in kg
  private Float volumeCapacity; // e.g., volume capacity in m^3
  private Float availableCapacity; // current available weight capacity
  private Float availableVolumeCapacity; // current available volume capacity
  private VehicleStatus vehicleStatus;

  // No-arg constructor
  public VehicleResponse() {
  }

  // All-args constructor (optional, but can be useful)
  public VehicleResponse(String registrationNumber, String vehicleType, Float capacity, Float volumeCapacity, Float availableCapacity, Float availableVolumeCapacity, VehicleStatus vehicleStatus) {
    this.registrationNumber = registrationNumber;
    this.vehicleType = vehicleType;
    this.capacity = capacity;
    this.volumeCapacity = volumeCapacity;
    this.availableCapacity = availableCapacity;
    this.availableVolumeCapacity = availableVolumeCapacity;
    this.vehicleStatus = vehicleStatus;
  }

  // Getters and Setters
  public String getRegistrationNumber() {
    return registrationNumber;
  }
  public void setRegistrationNumber(String registrationNumber) {
    this.registrationNumber = registrationNumber;
  }
  public String getVehicleType() {
    return vehicleType;
  }
  public void setVehicleType(String vehicleType) {
    this.vehicleType = vehicleType;
  }
  public Float getCapacity() {
    return capacity;
  }
  public void setCapacity(Float capacity) {
    this.capacity = capacity;
  }
  public Float getVolumeCapacity() {
    return volumeCapacity;
  }
  public void setVolumeCapacity(Float volumeCapacity) {
    this.volumeCapacity = volumeCapacity;
  }
  public Float getAvailableCapacity() {
    return availableCapacity;
  }
  public void setAvailableCapacity(Float availableCapacity) {
    this.availableCapacity = availableCapacity;
  }
  public Float getAvailableVolumeCapacity() {
    return availableVolumeCapacity;
  }
  public void setAvailableVolumeCapacity(Float availableVolumeCapacity) {
    this.availableVolumeCapacity = availableVolumeCapacity;
  }
  public VehicleStatus getVehicleStatus() {
    return vehicleStatus;
  }
  public void setVehicleStatus(VehicleStatus vehicleStatus) {
    this.vehicleStatus = vehicleStatus;
  }
}